import os

# Where the labs will live inside your repo
BASE_DIR = "labs/python_course/labs"

# List of labs you want generated
LABS = {
    1: "hello_world",
    2: "variables",
    3: "file_reader",
    4: "functions",
    5: "loops_conditionals",
    6: "lists_dicts",
    7: "string_processing",
    8: "simple_log_parser",
    9: "error_handling",
    10: "mini_cli",
    11: "process_list_monitor",
    12: "network_port_monitor",
    13: "filesystem_monitor",
    14: "cron_monitor",
    15: "user_account_monitor",
    16: "group_membership_monitor",
    17: "kernel_param_monitor",
    18: "kernel_module_monitor",
    19: "service_status_monitor",
    20: "package_version_monitor",
    21: "open_fd_monitor",
    22: "network_connection_monitor",
    23: "dns_monitor",
    24: "env_path_monitor",
    25: "systemd_unit_monitor",
    26: "process_tree_monitor",
    27: "resource_usage_monitor",
    28: "env_var_monitor",
    29: "capability_monitor",
    30: "entropy_monitor",
    31: "time_drift_monitor",
    32: "cpu_freq_monitor",
    33: "memory_map_monitor",
    34: "route_drift_monitor",
    35: "syscall_monitor",
    36: "kernel_log_monitor",
}

README_TEMPLATE = """# Lab {num} — {title}

Auto-generated by build_labs.py
"""

MAIN_TEMPLATE = """# Lab {num} — {title}
# Auto-generated main.py

def main():
    print("Running Lab {num}: {title}")

if __name__ == "__main__":
    main()
"""

UTILS_TEMPLATE = """# utils.py for Lab {num}
# Auto-generated

def placeholder():
    return "Lab {num} utils loaded"
"""

def create_lab(num, name):
    lab_dir = os.path.join(BASE_DIR, f"lab_{num}_{name}")
    os.makedirs(lab_dir, exist_ok=True)

    title = name.replace("_", " ").title()

    with open(os.path.join(lab_dir, "README.md"), "w") as f:
        f.write(README_TEMPLATE.format(num=num, title=title))

    with open(os.path.join(lab_dir, "main.py"), "w") as f:
        f.write(MAIN_TEMPLATE.format(num=num, title=title))

    with open(os.path.join(lab_dir, "utils.py"), "w") as f:
        f.write(UTILS_TEMPLATE.format(num=num))

    print(f"[+] Created Lab {num}: {lab_dir}")

def main():
    print("=== Building Python Course Labs ===")
    os.makedirs(BASE_DIR, exist_ok=True)

    for num, name in LABS.items():
        create_lab(num, name)

    print("\nAll labs generated successfully.")

if __name__ == "__main__":
    main()
